# import json
# import os

# def process_amg_data():
#     # 定义文件路径
#     # train_file = "/home/chenhui/EasyR1/AMG_train_grpo.json"
#     # test_file = "/home/chenhui/EasyR1/AMG_test_grpo.json"
#     # output_file = "/home/chenhui/EasyR1/AMG-An-Attributing-Multi-modal-Fake-News-Dataset/dataset/total.json"
#     train_file = "/home/chenhui/EasyR1/train_1200tool.json"
#     test_file = "/home/chenhui/EasyR1/val_1000grpo.json"
#     output_file = "/home/chenhui/EasyR1/MMFakeBench_val/total.json"
    
#     # 确保输出目录存在
#     output_dir = os.path.dirname(output_file)
#     if not os.path.exists(output_dir):
#         os.makedirs(output_dir)
    
#     # 处理数据
#     processed_data = []
    
#     # 处理训练数据
#     if os.path.exists(train_file):
#         with open(train_file, 'r', encoding='utf-8') as f:
#             train_data = json.load(f)
        
#         for item in train_data:
#             processed_item = {
#                 "images": item.get("images", []),
#                 "answer": item.get("answer", ""),
#                 "label": 1 if item.get("answer") == "visual_veracity_distortion" else 0
#             }
#             processed_data.append(processed_item)
    
#     # 处理测试数据
#     if os.path.exists(test_file):
#         with open(test_file, 'r', encoding='utf-8') as f:
#             test_data = json.load(f)
        
#         for item in test_data:
#             processed_item = {
#                 "images": item.get("images", []),
#                 "answer": item.get("answer", ""),
#                 "label": 1 if item.get("answer") == "Image Fabrication" else 0
#             }
#             processed_data.append(processed_item)
    
#     # 保存处理后的数据
#     with open(output_file, 'w', encoding='utf-8') as f:
#         json.dump(processed_data, f, indent=2, ensure_ascii=False)
    
#     # 打印统计信息
#     total_count = len(processed_data)
#     image_fabrication_count = sum(1 for item in processed_data if item["label"] == 1)
#     other_count = total_count - image_fabrication_count
    
#     print(f"处理完成！")
#     print(f"总数据条数: {total_count}")
#     print(f"Image Fabrication 数量: {image_fabrication_count} (标签为1)")
#     print(f"其他类别数量: {other_count} (标签为0)")
#     print(f"数据已保存到: {output_file}")

# if __name__ == "__main__":
#     process_amg_data()

# import json
# import os

# def merge_detection_results():
#     # 定义文件路径
#     total_json_path = "/home/chenhui/EasyR1/MMFakeBench_val/total.json"
#     detection_results_path = "/home/chenhui/EasyR1/detection_results_MMFakeBench.json"
    
#     # 读取total.json文件
#     print("正在读取total.json文件...")
#     with open(total_json_path, 'r', encoding='utf-8') as f:
#         total_data = json.load(f)
    
#     # 读取检测结果文件
#     print("正在读取检测结果文件...")
#     with open(detection_results_path, 'r', encoding='utf-8') as f:
#         detection_data = json.load(f)
    
#     # 创建检测结果的查找字典
#     detection_dict = {}
#     for item in detection_data:
#         for image_path, prediction_info in item.items():
#             detection_dict[image_path] = prediction_info.get("diffusion_generated", "unknown")
    
#     print(f"检测结果字典包含 {len(detection_dict)} 个图像路径")
    
#     # 统计信息
#     found_count = 0
#     not_found_count = 0
#     authentic_count = 0
#     fake_count = 0
    
#     # 遍历total_data，添加prediction_tool1和label1
#     for item in total_data:
#         images = item.get("images", [])
#         if images:
#             # 取第一个图像路径（根据您的数据格式，每个item只有一个图像）
#             image_path = images[0] if isinstance(images, list) else images
            
#             # 在检测结果中查找
#             if image_path in detection_dict:
#                 prediction = detection_dict[image_path]
#                 item["prediction_tool1"] = prediction
#                 # 如果prediction为"authentic"，label1为0，否则为1
#                 item["label1"] = 0 if prediction == "Not generated by diffusion" else 1
#                 found_count += 1
                
#                 # 统计authentic和fake数量
#                 if prediction == "Not generated by diffusion":
#                     authentic_count += 1
#                 else:
#                     fake_count += 1
#             else:
#                 # 如果没有找到对应的检测结果，设置为unknown和label1=1
#                 item["prediction_tool1"] = "unknown"
#                 item["label1"] = 1
#                 not_found_count += 1
#                 print(f"警告: 未找到图像路径的检测结果: {image_path}")
#         else:
#             # 如果没有图像路径，设置为unknown和label1=1
#             item["prediction_tool1"] = "unknown"
#             item["label1"] = 1
#             not_found_count += 1
#             print(f"警告: 数据项缺少图像路径")
    
#     # 保存更新后的数据
#     print("正在保存更新后的数据...")
#     with open(total_json_path, 'w', encoding='utf-8') as f:
#         json.dump(total_data, f, indent=2, ensure_ascii=False)
    
#     # 打印统计信息
#     print("\n=== 合并完成统计 ===")
#     print(f"总数据项数: {len(total_data)}")
#     print(f"成功匹配的项数: {found_count}")
#     print(f"未匹配的项数: {not_found_count}")
#     print(f"检测为authentic的项数: {authentic_count} (label1=0)")
#     print(f"检测为fake/unknown的项数: {fake_count + not_found_count} (label1=1)")
#     print(f"数据已更新并保存到: {total_json_path}")

# if __name__ == "__main__":
#     merge_detection_results()

# import json
# import os

# def merge_detection_results():
#     # 定义文件路径
#     # total_json_path = "/home/chenhui/EasyR1/AMG-An-Attributing-Multi-modal-Fake-News-Dataset/dataset/total.json"
#     # detection_results_path = "/home/chenhui/EasyR1/detection_results.json"
#     total_json_path = "/home/chenhui/EasyR1/MMFakeBench_val/total.json"
#     detection_results_path = "/home/chenhui/EasyR1/detection_results_MMFakeBench.json"
#     # 读取total.json文件
#     with open(total_json_path, 'r', encoding='utf-8') as f:
#         total_data = json.load(f)
    
#     # 读取detection_results.json文件
#     with open(detection_results_path, 'r', encoding='utf-8') as f:
#         detection_results = json.load(f)
    
#     # 创建检测结果的查找字典，便于快速查询
#     detection_dict = {}
#     for item in detection_results:
#         for image_path, detection_info in item.items():
#             detection_dict[image_path] = detection_info
    
#     # 统计信息
#     found_count = 0
#     not_found_count = 0
    
#     # 遍历total_data，添加新的键值对
#     for item in total_data:
#         images = item.get("images", [])
#         if images:  # 确保images列表不为空
#             image_path = images[0]  # 取第一个图像路径
            
#             if image_path in detection_dict:
#                 detection_info = detection_dict[image_path]
                
#                 # 处理diffusion_generated
#                 diffusion_result = detection_info.get("diffusion_generated", "")
#                 item["prediction_tool2"] = diffusion_result
#                 item["label2"] = 0 if diffusion_result == "Not generated by diffusion" else 1
                
#                 # 处理manipulated
#                 manipulated_result = detection_info.get("manipulated", "")
#                 item["prediction_tool3"] = manipulated_result
#                 item["label3"] = 0 if manipulated_result == "Not Manipulated" else 1
                
#                 found_count += 1
#             else:
#                 # 如果没有找到对应的检测结果，设置默认值
#                 item["prediction_tool2"] = "Not found"
#                 item["label2"] = -1  # 用-1表示未找到
#                 item["prediction_tool3"] = "Not found"
#                 item["label3"] = -1  # 用-1表示未找到
                
#                 not_found_count += 1
#         else:
#             # 如果没有图像路径，设置默认值
#             item["prediction_tool2"] = "No image"
#             item["label2"] = -1
#             item["prediction_tool3"] = "No image"
#             item["label3"] = -1
    
#     # 保存更新后的数据回total.json
#     with open(total_json_path, 'w', encoding='utf-8') as f:
#         json.dump(total_data, f, indent=2, ensure_ascii=False)
    
#     # 打印统计信息
#     print(f"处理完成！")
#     print(f"总数据条数: {len(total_data)}")
#     print(f"成功匹配的图片数: {found_count}")
#     print(f"未找到检测结果的图片数: {not_found_count}")
    
#     # 统计label2和label3的分布
#     label2_counts = {}
#     label3_counts = {}
    
#     for item in total_data:
#         label2 = item.get("label2", -1)
#         label3 = item.get("label3", -1)
        
#         label2_counts[label2] = label2_counts.get(label2, 0) + 1
#         label3_counts[label3] = label3_counts.get(label3, 0) + 1
    
#     print(f"\n=== label2 分布 ===")
#     for label, count in sorted(label2_counts.items()):
#         status = "Not generated by diffusion" if label == 0 else "Generated by diffusion" if label == 1 else "Not found/No image"
#         print(f"label2={label} ({status}): {count} 条")
    
#     print(f"\n=== label3 分布 ===")
#     for label, count in sorted(label3_counts.items()):
#         status = "Not Manipulated" if label == 0 else "Manipulated" if label == 1 else "Not found/No image"
#         print(f"label3={label} ({status}): {count} 条")

# if __name__ == "__main__":
#     merge_detection_results()

# import json
# import os

# def calculate_accuracy():
#     # 定义文件路径
#     # total_json_path = "/home/chenhui/EasyR1/AMG-An-Attributing-Multi-modal-Fake-News-Dataset/dataset/total.json"
#     total_json_path = "/home/chenhui/EasyR1/MMFakeBench_val/total.json"
#     # 读取total.json文件
#     with open(total_json_path, 'r', encoding='utf-8') as f:
#         total_data = json.load(f)
    
#     # 初始化计数器
#     total_count = len(total_data)
#     label1_correct = 0
#     label2_correct = 0
#     label3_correct = 0
    
#     label1_valid_count = 0
#     label2_valid_count = 0
#     label3_valid_count = 0
    
#     # 遍历数据，计算准确率
#     for item in total_data:
#         true_label = item.get("label")
#         # label1 = item.get("label1")
#         label2 = item.get("label2")
#         label3 = item.get("label3")
        
#         # # 检查label1是否有效（不是-1）
#         # if label1 is not None and label1 != -1:
#         #     label1_valid_count += 1
#         #     if label1 == true_label:
#         #         label1_correct += 1
        
#         # 检查label2是否有效（不是-1）
#         if label2 is not None and label2 != -1:
#             label2_valid_count += 1
#             if label2 == true_label:
#                 label2_correct += 1
        
#         # 检查label3是否有效（不是-1）
#         if label3 is not None and label3 != -1:
#             label3_valid_count += 1
#             if label3 == true_label:
#                 label3_correct += 1
    
#     # 计算准确率
#     # accuracy1 = label1_correct / label1_valid_count if label1_valid_count > 0 else 0
#     accuracy2 = label2_correct / label2_valid_count if label2_valid_count > 0 else 0
#     accuracy3 = label3_correct / label3_valid_count if label3_valid_count > 0 else 0
    
#     # 打印结果
#     print("=== 准确率计算结果 ===")
#     print(f"总数据条数: {total_count}")
#     # print(f"\nlabel1 准确率:")
#     # print(f"  有效样本数: {label1_valid_count}")
#     # print(f"  正确预测数: {label1_correct}")
#     # print(f"  准确率: {accuracy1:.4f} ({accuracy1*100:.2f}%)")
    
#     print(f"\nlabel2 准确率:")
#     print(f"  有效样本数: {label2_valid_count}")
#     print(f"  正确预测数: {label2_correct}")
#     print(f"  准确率: {accuracy2:.4f} ({accuracy2*100:.2f}%)")
    
#     print(f"\nlabel3 准确率:")
#     print(f"  有效样本数: {label3_valid_count}")
#     print(f"  正确预测数: {label3_correct}")
#     print(f"  准确率: {accuracy3:.4f} ({accuracy3*100:.2f}%)")

# if __name__ == "__main__":
#     calculate_accuracy()


import json
import os

def calculate_accuracy():
    # 定义文件路径
    # total_json_path = "/home/chenhui/EasyR1/AMG-An-Attributing-Multi-modal-Fake-News-Dataset/dataset/total.json"
    total_json_path = "/home/chenhui/EasyR1/MMFakeBench_val/total.json"
    # 读取total.json文件
    with open(total_json_path, 'r', encoding='utf-8') as f:
        total_data = json.load(f)
    
    # 初始化计数器
    total_count = len(total_data)
    combined_correct = 0
    
    # 遍历数据，计算准确率
    for item in total_data:
        true_label = item.get("label")
        label2 = item.get("label2")
        label3 = item.get("label3")
        
        # 计算组合预测标签：当label2和label3都为0时预测为0，否则为1
        if label2 is not None and label3 is not None and label2 != -1 and label3 != -1:
            if label2 == 0 and label3 == 0:
                predicted_label = 0
            else:
                predicted_label = 1
            
            # 检查预测是否正确
            if predicted_label == true_label:
                combined_correct += 1
    
    # 计算组合预测的准确率
    combined_accuracy = combined_correct / total_count if total_count > 0 else 0
    
    # 打印结果
    print("=== 准确率计算结果 ===")
    print(f"总数据条数: {total_count}")
    print(f"\n组合预测规则: 当label2和label3都为0时预测为0，否则为1")
    print(f"正确预测数: {combined_correct}")
    print(f"准确率: {combined_accuracy:.4f} ({combined_accuracy*100:.2f}%)")

if __name__ == "__main__":
    calculate_accuracy()